#!/bin/sh

# Usage: farm_list
#
# This script creates batch_krun and jscript_krun in batch_files directory
# and submits the job to the farms
#
# Feb. 22, 2011 Zhihong Ye
#

#home=/work/halla/solid/yez/SIDIS_Generator/test2
home=${PWD}
# The directory where replay_script is
# Event you want to start with,gtotal=-1 means to replay all
username=${USER}@jlab.org    # email which will be notify when the job is done
#
# Check whether the raw data are in cache or not
#

#
# Function to check if input is an integer
#
is_integer() {
 case $1 in
  *[!0-9]*) return 1;;
  *) return 0;;
 esac
}

TARGET=$1
KIN=$2

if ! [ -d batch_files ]
	then 
	echo "----------------------------------------------------------------"
	echo "I need batch_files directory. I am going to create it"
	echo  
	mkdir batch_files
    fi
    
#
    echo
#
# Write file batch_krun
#
    rm -f batch_files/batch_${TARGET}_${KIN}
    echo "#!/bin/sh" > batch_files/batch_${TARGET}_${KIN}
    echo "cd "${home}"/" >>batch_files/batch_${TARGET}_${KIN}
    echo " ">>batch_files/batch_${TARGET}_${KIN}
    echo "./New_Yield "${TARGET}"_kin"${KIN}".dat">>batch_files/batch_${TARGET}_${KIN}
#  
    chmod +x batch_files/batch_${TARGET}_${KIN}

    
    echo "batch_files/batch_"${TARGET}_${KIN}" has been created!"
    echo " "
    
#
# Write the jsub script
#
    rm -f batch_files/jscript_${TARGET}_${KIN}
    echo "PROJECT     triton" > batch_files/jscript_${TARGET}_${KIN}
    echo "COMMAND     "$home"/batch_files/batch_"${TARGET}_${KIN} >>batch_files/jscript_${TARGET}_${KIN}
    echo "JOBNAME     xs_"${TARGET}_${KIN} >>batch_files/jscript_${TARGET}_${KIN}
    echo "TRACK       analysis" >> batch_files/jscript_${TARGET}_${KIN}
    echo "TIME        2000" >>batch_files/jscript_${TARGET}_${KIN}
    echo "MEMORY      4000 MB" >>batch_files/jscript_${TARGET}_${KIN}
    echo "OS          centos7" >>batch_files/jscript_${TARGET}_${KIN}
    
    echo "batch_files/jscript_"${TARGET}_${KIN}" has been created."
    echo " " 
    echo "Now, let us wait for the farms..."
    echo " "
#
# Submit job to the farm
   #jsub batch_files/jscript_${TARGET}_${KIN}
   swif add-jsub -workflow tritium_analysis -create -script ./batch_files/jscript_${TARGET}_${KIN}
   swif run -workflow tritium_analysis
#
#
    echo "Job "${TARGET}_${KIN} "has been submited!"
    echo
    echo
#
    sleep 0.5
    
