#!/bin/sh

# Usage: farm_list
#
# This script creates batch_krun and jscript_krun in batch_files directory
# and submits the job to the farms
#
# Feb. 22, 2011 Zhihong Ye
# --- Feb. 20 2018 updated for Triton
#

home=/work/halla/triton/MARATHON_Replay/
# home=$(PWD)     
# The directory where replay_script is
# Event you want to start with,gtotal=-1 means to replay all
gstart=1
#gtotal=50000
gtotal=-1
username=${USER}@jlab.org    # email which will be notify when the job is done
#
# Check whether the raw data are in cache or not
#
RAWDIR=/mss/halla/triton/raw/
CACHEDIR=/cache/mss/halla/triton/raw/

#
# Function to check if input is an integer
#
is_integer() {
 case $1 in
  *[!0-9]*) return 1;;
  *) return 0;;
 esac
}

krun=$1
echo $krun

COUNT=0
#If the data is already in the cahce, replay it
if [ -e $CACHEDIR"/triton_"$krun".dat."$COUNT ]; then

#
# Verify if batch_files and .tmp.REPLAY exist
#
    if ! [ -d batch_files ]
	then 
	echo "----------------------------------------------------------------"
	echo "I need batch_files directory. I am going to create it"
	echo  
	mkdir batch_files
    fi
    
#
    echo
#
# Write file batch_krun
#
    rm -f batch_files/batch_${krun}
    echo "#!/bin/sh" > batch_files/batch_${krun}
    echo "cd " ${home}"/replay" >>batch_files/batch_${krun}
    echo "rm -f ./Rootfiles/triton_"${krun}"*.root" >>batch_files/batch_${krun}
    echo " ">>batch_files/batch_${krun}
    echo "./fullReplay "${krun} >>batch_files/batch_${krun}
#  
    chmod +x batch_files/batch_${krun}
    
    echo "batch_files/batch_"${krun}" has been created!"
    echo " "
    
#
# Write the jsub script
#
    rm -f batch_files/jscript_${krun}
    echo "PROJECT     triton" > batch_files/jscript_${krun}
    echo "COMMAND     "$home"/batch_farm/batch_files/batch_"${krun} >>batch_files/jscript_${krun}
    echo "JOBNAME     H3.analysis"${krun} >>batch_files/jscript_${krun}
    echo "TRACK       analysis" >> batch_files/jscript_${krun}
    echo "TIME        4000" >>batch_files/jscript_${krun}
    echo "MEMORY      1800 MB" >>batch_files/jscript_${krun}
    echo "OS          centos7" >>batch_files/jscript_${krun}
 # echo "MAIL:       "$username >>batch_files/jscript_${krun}
 # echo "INPUT_FILES:"$home"/replay/HRS.odef" >>batch_files/jscript_L_${krun}
    
    echo "batch_files/jscript_"${krun}" has been created."
    echo " " 
    echo "Now, let us wait for the farms..."
    echo " "
################################
#    Submit job to the farm    #  
################################
    #jsub batch_files/jscript_${krun}
    #swif add-jsub -workflow h3_analysis -create -script ./batch_files/jscript_${krun}
    #swif run -workflow h3_analysis
################################
################################

    echo "Job "${krun} "has been submited!"
    echo
    echo
#
    sleep 1
    
else
    while [ $COUNT -lt 10 ]; do
	if [ -e $RAWDIR"/triton_"${krun}".dat."$COUNT ]; then
	    jcache get $RAWDIR"/triton_"${krun}".dat."$COUNT
	    echo "         ===== cache the raw file triton_"${krun}".dat."$COUNT
	    let COUNT=COUNT+1
	else
	    COUNT=10
	fi
    done
    echo
    echo "***** Cache the raw files, please do your replay later when it is done *****"
echo

fi

echo
echo "***** Good Bye and thank you for using the script *****"
echo
